### ISSUE TITLE
请问有docker部署方式嘛？

### ISSUE THREAD

**Issue by usyunfei** [bclswl0827/ChatGemini#1]
请问有docker部署方式嘛？同时，是否能增加给网站加密码的功能？

**Comment by bclswl0827** [comment]
Docker 部署方式稍候加上，密码访问也计划在后续更新中加上

**Comment by li88iioo** [comment]
自己构建就好了
```
sudo mkdir -p /opt/docker/chatgemini
sudo chown $USER:$USER /opt/docker/chatgemini
cd /opt/docker/chatgemini
git clone https://github.com/bclswl0827/ChatGemini.git .
```
`nano Dockerfile`
```
# 使用官方 Node.js 基础镜像
FROM node:lts

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 复制项目文件到工作目录
COPY . .

# 暴露容器运行时的端口
EXPOSE 3000

# 定义运行时执行的命令
CMD ["npm", "start"]

```
`
nano docker-compose.yml
`
```
version: '3.8'
services:
  chatgemini:
    build: .
    ports:
      - "30000:3000" # 将容器的 30000 端口映射到宿主机的 3000 端口
    volumes:
      - .:/app # 映射当前目录到容器的 /app
      - /app/node_modules # 避免覆盖容器内的 node_modules
```
` 
nano .env
`
```
# 站点标题，会显示在浏览器标签页上
# 默认值：ChatGemini
REACT_APP_TITLE_SITE=
# 站点名称，会显示在页面头部
# 默认值：Gemini Pro
REACT_APP_TITLE_HEADER=
# Gemini API 密钥
# 默认值：<空>
REACT_APP_GEMINI_API_KEY=AIbcsssas
# 逐字输出 Gemini 回应
# 默认值：true
REACT_APP_GEMINI_API_SSE=
# 自定义 Gemini API 地址
# Default: <空>
REACT_APP_GEMINI_API_URL=

```
```
docker-compose up --build -d
```
