### ISSUE TITLE
Docker 运行失败

### ISSUE THREAD

**Issue by wang20150419** [bclswl0827/ChatGemini#5]
很喜欢这个界面设计。
但是按说明使用 docker 部署无法使用。容器能启动，但网页无法访问。
配置了 REACT_APP_GEMINI_API_KEY 和 REACT_APP_PASSCODE_MD5 两个环境变量（用了引号）。
同样的 KEY，在项目 https://github.com/babaohuang/GeminiProChat 里正常。

如何解决？

**Comment by bclswl0827** [comment]
> 容器能启动，但网页无法访问。

应用会在容器开始运行时先执行 `npm run build`，构建完成后才会启动 Nginx，这一步需要一些时间

**Comment by chenweiask** [comment]
> 很喜欢这个界面设计。 但是按说明使用 docker 部署无法使用。容器能启动，但网页无法访问。 配置了 REACT_APP_GEMINI_API_KEY 和 REACT_APP_PASSCODE_MD5 两个环境变量（用了引号）。 同样的 KEY，在项目 https://github.com/babaohuang/GeminiProChat 里正常。
> 
> 如何解决？

看看docker运行日志报错内容咯。
我用Portainer加载docker compose运行，除了镜像下载速度慢，其他没问题。下载速度是网络的问题。
我的compose供你参考：
```
services:
    chatgemini:
        container_name: chatgemini
        restart: unless-stopped
        ports:
            - 8080:8080 #冒号前面填写你想要的端口
        environment:
            - REACT_APP_GEMINI_API_KEY=你的API Key #填写你的API Key，有没有引号都可以
            - REACT_APP_GEMINI_API_URL=https://xxx #代理地址，如果遇到“User location is not supported for the API use”的提示，就要部署代理。代理部署方法见[palm-netlify-proxy](https://github.com/antergone/palm-netlify-proxy)
            - REACT_APP_TITLE_SITE=网站标题
            - REACT_APP_GEMINI_API_SSE=true #如果不要逐字输出，就删掉这条
            - REACT_APP_TITLE_HEADER=网页标题
            - REACT_APP_PASSCODE_MD5=xxx #MD5格式的密码
        image: ghcr.io/bclswl0827/chatgemini
```
